import { DailyQuote } from './types';

export const quotes: DailyQuote[] = [
  {
    id: '1',
    text: '우리가 볼 수 없는 것들이 우리를 가장 많이 변화시킨다.',
    source: '채식주의자',
    author: '한강',
    genre: '소설',
  },
  {
    id: '2',
    text: '사람은 자신이 사랑하는 것을 닮아간다.',
    source: '어린 왕자',
    author: '생텍쥐페리',
    genre: '소설',
  },
  {
    id: '3',
    text: '가장 어두운 밤도 끝날 것이고, 태양은 떠오를 것이다.',
    source: '레 미제라블',
    author: '빅토르 위고',
    genre: '소설',
  },
  {
    id: '4',
    text: '당신이 지금 이 자리에 있는 것만으로도 충분하다.',
    source: '82년생 김지영',
    author: '조남주',
    genre: '소설',
  },
  {
    id: '5',
    text: '모든 끝에는 시작이 숨어 있다.',
    source: '아몬드',
    author: '손원평',
    genre: '소설',
  },
  {
    id: '6',
    text: '나는 나를 사랑하는 일을 게을리하지 않겠다.',
    source: '나는 나로 살기로 했다',
    author: '김수현',
    genre: '에세이',
  },
  {
    id: '7',
    text: '불완전함이 아름다움이고, 광기가 천재성이며, 우스꽝스러운 것이 훨씬 낫다.',
    source: '매릴린 먼로 어록',
    author: '매릴린 먼로',
    genre: '명언',
  },
  {
    id: '8',
    text: '천천히 가도 괜찮아. 멈추지만 않으면 돼.',
    source: '논어',
    author: '공자',
    genre: '명언',
  },
  {
    id: '9',
    text: '봄이 오면 꽃이 피고, 여름이 오면 새가 운다. 가을 달 겨울 소나무, 한가롭기 그지없어라.',
    source: '청허집',
    author: '서산대사',
    genre: '시',
  },
  {
    id: '10',
    text: '내가 그의 이름을 불러 주었을 때, 그는 나에게로 와서 꽃이 되었다.',
    source: '꽃',
    author: '김춘수',
    genre: '시',
  },
  {
    id: '11',
    text: '나보기가 역겨워 가실 때에는 말없이 고이 보내드리오리다.',
    source: '진달래꽃',
    author: '김소월',
    genre: '시',
  },
  {
    id: '12',
    text: '두 갈래 길이 숲 속에 있었고, 나는 덜 다닌 길을 택했다.',
    source: '가지 않은 길',
    author: '로버트 프로스트',
    genre: '시',
  },
  {
    id: '13',
    text: '언제나 마음에 해가 뜨고 있다면, 그것으로 충분하다.',
    source: '어느 날 고궁을 나오면서',
    author: '김수영',
    genre: '시',
  },
  {
    id: '14',
    text: '삶이 그대를 속일지라도 슬퍼하거나 노하지 말라.',
    source: '삶이 그대를 속일지라도',
    author: '푸시킨',
    genre: '시',
  },
  {
    id: '15',
    text: '진정한 여행의 발견은 새로운 풍경을 보는 것이 아니라, 새로운 눈을 갖는 것이다.',
    source: '잃어버린 시간을 찾아서',
    author: '마르셀 프루스트',
    genre: '소설',
  },
  {
    id: '16',
    text: '행복은 완성된 것이 아니라 지금 이 순간 만들어가는 과정이다.',
    source: '행복의 정복',
    author: '버트런드 러셀',
    genre: '에세이',
  },
  {
    id: '17',
    text: '우리는 우리가 반복적으로 행하는 것이다. 탁월함은 행동이 아니라 습관이다.',
    source: '니코마코스 윤리학',
    author: '아리스토텔레스',
    genre: '명언',
  },
  {
    id: '18',
    text: '책 한 권을 읽는다는 것은 새로운 삶을 시작하는 것이다.',
    source: '소설에서 먼 길을 돌아',
    author: '박완서',
    genre: '에세이',
  },
  {
    id: '19',
    text: '아무것도 하지 않으면 아무것도 변하지 않는다.',
    source: '파친코',
    author: '이민진',
    genre: '소설',
  },
  {
    id: '20',
    text: '시간은 우리가 가진 가장 귀중한 자원이다. 그것은 우리가 만들 수 없는 유일한 것이다.',
    source: '사피엔스',
    author: '유발 하라리',
    genre: '에세이',
  },
  {
    id: '21',
    text: '두려움은 실패에서 오는 것이 아니라, 시도하지 않는 것에서 온다.',
    source: '인간실격',
    author: '다자이 오사무',
    genre: '소설',
  },
  {
    id: '22',
    text: '별을 보려면 어두운 밤이 필요하다.',
    source: '페르시아 속담',
    genre: '명언',
  },
  {
    id: '23',
    text: '꿈을 잡을 수 없다면, 적어도 꿈을 꿀 수 있다.',
    source: '위대한 개츠비',
    author: '스콧 피츠제럴드',
    genre: '소설',
  },
  {
    id: '24',
    text: '오늘 할 수 있는 일을 내일로 미루지 말라.',
    source: '벤저민 프랭클린 어록',
    author: '벤저민 프랭클린',
    genre: '명언',
  },
  {
    id: '25',
    text: '당신이 있는 곳에서, 당신이 가진 것으로, 당신이 할 수 있는 것을 하라.',
    source: '루즈벨트 어록',
    author: '시어도어 루즈벨트',
    genre: '명언',
  },
  {
    id: '26',
    text: '가장 큰 영광은 결코 넘어지지 않는 것이 아니라, 넘어질 때마다 일어서는 것이다.',
    source: '넬슨 만델라 어록',
    author: '넬슨 만델라',
    genre: '명언',
  },
  {
    id: '27',
    text: '상처가 아물면 그 자리에 단단한 것이 생긴다.',
    source: '달러구트 꿈 백화점',
    author: '이미예',
    genre: '소설',
  },
  {
    id: '28',
    text: '당신은 당신이 생각하는 것보다 훨씬 강하고, 용감하며, 영리하다.',
    source: '곰돌이 푸',
    author: 'A. A. 밀른',
    genre: '소설',
  },
  {
    id: '29',
    text: '삶은 우리가 멈추지 않는 한, 언제나 새로운 기회를 품고 있다.',
    source: '어느 작가의 고백',
    genre: '에세이',
  },
  {
    id: '30',
    text: '내가 경험한 가장 아름다운 것은 신비로움이다. 그것이 모든 진정한 예술과 과학의 원천이다.',
    source: '알베르트 아인슈타인 어록',
    author: '알베르트 아인슈타인',
    genre: '명언',
  },
  {
    id: '31',
    text: '마음이 가는 곳에 길이 있다.',
    source: '인도 속담',
    genre: '명언',
  },
  {
    id: '32',
    text: '혼자 가면 빨리 갈 수 있지만, 함께 가면 멀리 갈 수 있다.',
    source: '아프리카 속담',
    genre: '명언',
  },
  {
    id: '33',
    text: '현재 순간만이 실제로 살 수 있는 순간이다.',
    source: '틱낫한 어록',
    author: '틱낫한',
    genre: '에세이',
  },
  {
    id: '34',
    text: '글쓰기는 자신을 발견하는 일이다.',
    source: '작가의 일',
    author: '헨리 밀러',
    genre: '에세이',
  },
  {
    id: '35',
    text: '모든 것이 가능한 척 행동하면, 모든 것이 가능해진다.',
    source: '윌리엄 제임스 어록',
    author: '윌리엄 제임스',
    genre: '명언',
  },
];

export function getDailyQuote(): DailyQuote {
  const today = new Date();
  const startOfYear = new Date(today.getFullYear(), 0, 0);
  const diff = today.getTime() - startOfYear.getTime();
  const dayOfYear = Math.floor(diff / (1000 * 60 * 60 * 24));
  return quotes[dayOfYear % quotes.length];
}
